# source/tools/kubernetes/dask-kubernetes/gpu-worker-spec.yaml
kind: Pod
metadata:
  labels:
    cluster_type: dask
    dask_type: GPU_worker
spec:
  restartPolicy: Never
  containers:
    - image: nvcr.io/nvidia/rapidsai/rapidsai-core:22.08-cuda11.5-runtime-ubuntu20.04-py3.9
      imagePullPolicy: IfNotPresent
      env:
        - name: DISABLE_JUPYTER
          value: "true"
      args: [dask-cuda-worker, $(DASK_SCHEDULER_ADDRESS), --rmm-managed-memory]
      name: dask-cuda
      resources:
        limits:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1 # requesting 1 GPU
        requests:
          cpu: "2"
          memory: 3G
          nvidia.com/gpu: 1 # requesting 1 GPU
